[package]
name = "ibr"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.9", features = ["derive"] }
env_logger = "0.11.3"
serde = "1.0.204"
serde_json = "1.0.120"
